name: ARP E2E tests

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - "**.md"
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - "**.md"


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Download dependencies
        run: go mod tidy

      - name: Run tests
        run:  make test-e2e

